### ISSUE TITLE
Successfully installed but 'wp rocket' commands not working

### ISSUE THREAD

**Issue by akarmach** [wp-media/wp-rocket-cli#14]
Hello, I am a bit of a newb with Composer. I ran 'wp package install geekpress/wp-rocket-cli' and received a successful message, but no 'wp rocket' commands work (other wp commands are fine). Am I missing a step? Thanks so much!

**Comment by russellmann** [comment]
Same issue. Here's the message and confirmation that the package is installed.

wp rocket
Error: 'rocket' is not a registered wp command. See 'wp help' for available commands.
-------------
php -d memory_limit=512M "$(which wp)" --allow-root package list
+-------------------------+----------------+------------+-----------+----------------+
| name                    | authors        | version    | update    | update_version |
+-------------------------+----------------+------------+-----------+----------------+
| GeekPress/wp-rocket-cli | WP Rocket Team | dev-master | available | dev-master     |
+-------------------------+----------------+------------+-----------+----------------+

**Comment by iCaspar** [comment]
Is this still an issue? If so, what (if anything) happens instead of the expected commands? Any error messages?

**Comment by remyperona** [comment]
Closing this as invalid as it's very old and likely no longer relevant
