### ISSUE TITLE
Add to Packagist

### ISSUE THREAD

**Issue by ronilaukkarinen** [wp-media/wp-rocket-cli#2]
Hello. I need to use this in my Capistrano setups, so a Packagist repo is needed. I went ahead and created one in https://packagist.org/packages/geekpress/wp-rocket-cli. I would gladly add you as a maintainer so you could setup a GitHub Service Hook for auto updates. Thanks!

**Comment by ethanclevenger91** [comment]
@GeekPress gonna just bump this. Kind of annoying to manually add the VCS info to every project using this, so would love to see this in Packagist.

**Comment by iCaspar** [comment]
This is now on packagist here: https://packagist.org/packages/wp-media/wp-rocket-cli
Thanks @ronilaukkarinen for maintaining at the other location in the (long) interim.

**Comment by ethanclevenger91** [comment]
@iCaspar Thanks! Tagging a new release while you're at it would be super helpful so everyone doesn't have to require dev-master.

**Comment by iCaspar** [comment]
@ethanclevenger91 We're going to give this project a bit of love in the next couple weeks, and will likely tag it once we've cleaned up a few of these other pending issues. :) Thanks for your patience!
